import { timer } from './modules/timer';
import { menu } from './modules/menu';
import { modal } from './modules/modal';
import { inputValidation } from './modules/inputValidation';
import { tabs } from './modules/tabs';
import { scroll } from './modules/scroll';
import { slider } from './modules/slider';
import { calculator } from './modules/calculator';
import { sendForm } from './modules/sendForm';

timer('22 january 2025');
menu();
modal();
scroll();
inputValidation();
tabs();
slider();
calculator(100);
sendForm({ formId: 'form1', animationId: 'form1-animation' });
sendForm({ formId: 'form2', animationId: 'form2-animation' });
sendForm({ formId: 'form3', animationId: 'form3-animation' });
